default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: izanagi_development
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: izanagi_test
  username: root
  password:
  host: localhost

production:
  <<: *default
  database: izanagi_production
  # wip
